[font]
size = 14.0

[font.bold]
family = "Fira Code"

[font.italic]
family = "Fira Code"

[font.normal]
family = "Fira Code"

[scrolling]
history = 1000
multiplier = 3

[window]
decorations = "full"
startup_mode = "Windowed"

[shell]
program = "/usr/bin/tmux"
